name: CI
on:
  push:
    branches: [ master, features ]
  pull_request:
    branches: [ master, features ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run tests
      run: yarn test
